INSERT INTO user VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), sysdate(), 'AB');
INSERT INTO user VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), sysdate(), 'Jill');
INSERT INTO user VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), sysdate(), 'Jam');